version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yyblog_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_net

  nginx:
    image: nginx:stable-alpine
    container_name: yyblog_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net


networks:
  laravel_net: